### ISSUE TITLE
simple bug I meet

### ISSUE THREAD

**Issue by BlenderCN** [feler404/ocvl-addon#11]
hello,I meet a problems when install addon
location: <unknown location>:-1
Traceback (most recent call last):
  File "/root/Blender/blender-280/2.80/scripts/startup/bl_ui/space_userpref.py", line 1809, in draw
    split.label(text=info["author"], translate=False)
TypeError: UILayout.label(): error with keyword argument "text" -  Function.text expected a string type, not tuple

and to

https://github.com/feler404/ocvl-addon/blob/3379bf842cdfd6e7d10209103a7d050e74b38a3f/__init__.py#L32

    "author": (
        "Dawid Aniol, ",
        "OCVL team, ",
        "Teredo team",
    ),

I try to change as 

"author": "Dawid Aniol,OCVL team,Teredo team",

then solve

**Comment by feler404** [comment]
Thank you @BlenderCN. FIxed in master.
