### ISSUE TITLE
OCVL clashing with Sverchok add-on....

### ISSUE THREAD

**Issue by enzyme69** [feler404/ocvl-addon#23]
<img width="1072" alt="Screen Shot 2019-08-09 at 8 10 42 pm" src="https://user-images.githubusercontent.com/3952687/62772004-d1191280-bae1-11e9-93e5-3a4d3317d0a8.png">

Not sure how to explain this, but OCVL addon seems to be affecting Sverchok nodes not in the good way... it clashes and making some nodes not working.

**Comment by zeffii** [comment]
i suspect after browsing some of this codebase, that some of the OCVL code is based on Sverchok's implementation of the node tree - i doubt we will change our code for this.

**Comment by zeffii** [comment]
ideally OCVL would prefix their Socket Types also with OCVL or something.

don't wait around for lazy people like me.

**Comment by zeffii** [comment]
on the other hand i do cordially recommend that @feler404  does prefix his classnames anyway.

**Comment by zeffii** [comment]
( we will be changing our socket classnames/bl_idnames to all have `Sv` prefix -- but it's a big job )

**Comment by feler404** [comment]
First OCVL was based on Sverchock and class ColorSocket is one of the classes which come from Sverchok. I will do a review I fix that. Probably the best way will add prefix class names as advised by @zeffii. @enzyme69  Thanks.

**Comment by zeffii** [comment]
very cool project btw @feler404 !

**Comment by feler404** [comment]
A make refactor Socket and Operator names, now should not appear conflicts with other addons. 

P.S. Tanks @zeffii sverchok was my first inspiration.
