### ISSUE TITLE
Video Sample node does not play when reopening the Blend

### ISSUE THREAD

**Issue by enzyme69** [feler404/ocvl-addon#26]
I tested the Video Sample with latest addon update, it is working fine everything is good. But if close Blender and reopen the BLEND, seems like the node tree is no longer streaming the video sample like before. Re-adding the node does not help.

Workaround for now is to delete the Video Sample node. Save the Blend. Reopen and re-add the Video Sample node to work...

**Comment by feler404** [comment]
Yes, this is strange, I must check to init method end globals for cashing camera devices.

**Comment by feler404** [comment]
I make update init and cleanup methods and now should work. Except that is a general issue when loading a file with nodes are loaded nodes but without data and is necessary to trigger every produce data node and force recalculate node.

**Comment by feler404** [comment]
Now I close this issue, for lacking data I create #31 . I find something else create another issue od maybe reopen this topic :)
