### ISSUE TITLE
Tried to understand "detection" but none works - eg Blob

### ISSUE THREAD

**Issue by enzyme69** [feler404/ocvl-addon#27]
<img width="798" alt="Screen Shot 2019-08-11 at 12 04 16 pm" src="https://user-images.githubusercontent.com/3952687/62828704-2feca200-bc30-11e9-9e26-5994ca240992.png">

I want to try Object Detect but seems like none of the node working, or am I missing something not sure if that keypoints etc is producing anything.

For example Simple Blob Detector node, I am not sure how this can actually work or should work but just it does not work on my computer?

**Comment by enzyme69** [comment]
Ideally I would like to detect a simple blob or ping pong ball maybe with color, and then pipe out the result into Blender 3D transform for further manipulation using SVerchok, AN, etc...

**Comment by feler404** [comment]
SimpleBlobDetector now is disabled 
```
        if self.loc_work_mode == "DETECT":
            pass
            # self._detect(instance)
        elif self.loc_work_mode == "COMPUTE":
            self._compute(instance)
        elif self.loc_work_mode == "DETECT-COMPUTE":
            pass
            # self._detect_and_compute(instance)
```
This class have different interfance for standard methos and don't fit to generic class OCVLFeature2DNode.  For this class I must prepare more elastic interface to generate instace this class.


Here is an interesting article about SimpleBlobDetection: 
https://www.learnopencv.com/blob-detection-using-opencv-python-c/

I think you should achieve your goal but you must extract/filter output from descriptors. When I resolve other issues which you reported to me  ;) I take this too.

**Comment by feler404** [comment]
For new a set status=ALPHA for this node, and until I don't refactor OCVLFeature2DNode will be invisible.

**Comment by feler404** [comment]
<img width="443" alt="Zrzut ekranu 2019-08-28 o 12 54 31" src="https://user-images.githubusercontent.com/4757634/63849822-1e76fa00-c993-11e9-874e-341be5fe94e7.png">
SimpleBlobDetector arleady is full functionality.
